Bugfix/258 header responsive
DigitalExcellence/dex-frontend pull request #291
Opened 2020-09-17 09:13 UTC by Ruby77

## Description

Make the header responsive for different screen sizes. I did this by adding bootstrap classes for a burger menu. And made this trigger by using typescript (and styled the navbar in the burger menu). (Because there a still no designs for the header, this will be used for a starting point for whenever the design updates)

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Make screen 767px wide. The links in the header should disappear and a burger menu should appear.

2. Click on the burger menu. The links should appear under the header, aligned to the left.

3. When you are logged in, you should be able to click on your account name. When clicking on your name, the logout text should appear under the current links.

## Link to issue

Closes: #258

2020-09-21 11:37 UTC, Brend-Smits commented
@Niekvandam and @liekevdvoort, mind reviewing this PR?

2020-09-21 12:16 UTC, liekevdvoort submitted a review, later dismissed

2020-09-21 12:52 UTC, Niekvandam submitted a review, later dismissed

2020-09-21 15:46 UTC, Brend-Smits requested changes
Functional, nice! Thanks for the PR!

2020-09-21 15:46 UTC, Brend-Smits commented on src/app/components/app-layout/app-layout.component.ts
> +  public toggleNavbar() {
```suggestion
  public toggleNavbar(): void {
```

2020-09-21 15:49 UTC, Brend-Smits requested changes

2020-09-21 15:49 UTC, Brend-Smits commented on CHANGELOG.md
>  - Changed footer styling to be responsive on small screens - [#163] (https://github.com/DigitalExcellence/dex-frontend/issues/163)
```suggestion
- Changed footer styling to be responsive on small screens - [#163](https://github.com/DigitalExcellence/dex-frontend/issues/163) 
```

2020-09-23 12:26 UTC, liekevdvoort submitted a review, later dismissed

2020-09-25 18:43 UTC, Brend-Smits approved these changes
You can merge this when you fix the conflicts

2020-09-28 08:04 UTC, Brend-Smits approved these changes

2020-09-28 08:06 UTC, liekevdvoort approved these changes

2020-09-28 08:08 UTC, merged