Feature/283 page discoverability
DigitalExcellence/dex-frontend pull request #295
Opened 2020-09-21 10:29 UTC by Niekvandam

## Description

Adding a basic form of SEO to the website, to get a small start on getting discovered by new visitors

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [X] I updated the changelog with an end-user readable description
-   [X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

### Check sitemap
1. Go to the root website /sitemap.xml
2. You should see an xml document which contains the sitemap

### Check robots.txt
1. Go to the root website /robots.txt
2. You should see a basic robots.txt file 

### Lazy loading images
1. Go to the website
2. Check if all images load correctly

## Link to issue

Closes: #282

2020-09-21 13:37 UTC, MaxKorlaar requested changes

2020-09-21 13:37 UTC, MaxKorlaar commented on CHANGELOG.md
> +- Added basic SEO for better google discoverability - [#283](https://github.com/orgs/DigitalExcellence/projects/11#card-45582851)
Changelog entry should link to issue page, not the issue card in the project overview 😃

2020-09-21 13:37 UTC, MaxKorlaar commented on src/sitemap.xml
> +    <url><loc>http://dex.software/home/account/login</loc><priority>0.5</priority></url>
These should refer to the canonical URLs on DeX, which are all secure (https), these URLs all redirect.

2020-09-21 13:37 UTC, MaxKorlaar commented on src/sitemap.xml
> +    <url><loc>http://dex.software/home/privacy</loc><priority>0.5</priority></url>
```suggestion
```
I don't think that the privacy policy is relevant for a sitemap. I leave it out on all my own sites. Search engines also decide what's important as well.

Also, if you were to leave it in, the URL's incorrect.

2020-09-21 13:37 UTC, MaxKorlaar commented on src/sitemap.xml
> +    <url><loc>http://dex.software/home/account/login</loc><priority>0.5</priority></url>
These URLs are all broken

2020-09-21 13:37 UTC, MaxKorlaar commented on src/index.html
> +  <meta name="description" content="Dex provides a platform for students to share and work on projects. Share, work on and create new projects on Dex">
```suggestion
  <meta name="description" content="DeX provides a platform for students, teachers and employees to share and work on projects. Share, work on and create new projects on DeX">
```

2020-09-21 16:13 UTC, Brend-Smits requested changes
Welcome and congrats on your first PR 🎉

2020-09-21 16:13 UTC, Brend-Smits commented on src/index.html
> +  <meta name="description" content="Dex provides a platform for students to share and work on projects. Share, work on and create new projects on Dex">
```suggestion
  <meta name="description" content="DeX provides a platform for students, teachers and employees to share and work on projects and ideas. Find, create, share and work on projects and ideas on DeX">
```
DeX is about projects AND ideas ;)

2020-09-22 08:43 UTC, juliaslaats reviewed
Looks good to me (but I'm not sure I understand enough of what you did to realise if anything is wrong)

2020-09-22 09:40 UTC, MaxKorlaar approved these changes

2020-09-22 09:41 UTC, Brend-Smits approved these changes

2020-09-22 12:52 UTC, merged