Feature/311 display project icon
DigitalExcellence/dex-frontend pull request #331
Opened 2020-10-26 09:17 UTC by Ruby77

## Description

Display project icon if an icon is uploaded, otherwise show the default placeholder.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Add a project with a project icon.
2. Go to the project overview and check if the project icon is shown.
3. Click on the project to navigate to the details page and also check here if the project icon is shown.
4. Highlight this project, navigate to the homepage. Refresh this page until the project is shown and check if the project icon is visible. 

5. (This is currently not working, but if you press 'Embed this' on the details page, the project icon will also show. This problem is already available in the project icon branch I'm building on.)

## Link to issue

Closes: #311

2020-10-27 08:22 UTC, waltersajtos requested changes

2020-10-27 08:22 UTC, waltersajtos commented on src/app/modules/highlight/top-highlight-cards/top-highlight-cards.component.ts
> +import { RESOURCE_CONFIG } from '../../../config/resource-config';
Make sure to use absolute paths

2020-10-27 08:22 UTC, waltersajtos commented on src/app/modules/project/embed/embed.component.ts
> +import { RESOURCE_CONFIG } from '../../../config/resource-config';
Same here.

2020-10-27 08:22 UTC, waltersajtos commented on src/app/modules/project/overview/overview.component.ts
> +  public getIconUrl(id: number): SafeUrl {
I see this function multiple times which isn't really dry.

2020-10-28 10:14 UTC, waltersajtos approved these changes
Changes were implemented properly, looks good!

2020-10-30 09:27 UTC, liekevdvoort approved these changes

2020-11-04 08:07 UTC, merged