Feature/362 implement new project detail
DigitalExcellence/dex-frontend pull request #379
Opened 2020-12-02 22:52 UTC by waltersajtos

## Description

Implement the modal-design of the project detail page

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Go to the project overview page and click a project
2. A modal should pop up with the project details

## Link to issue
#362 

Closes: #362

2020-12-02 23:07 UTC, Brend-Smits requested changes

2020-12-02 23:07 UTC, Brend-Smits commented on CHANGELOG.md
> +- Redesigned project details apge [#362](https://github.com/DigitalExcellence/dex-frontend/issues/362)
```suggestion
- Implemented redesigned project details page [#362](https://github.com/DigitalExcellence/dex-frontend/issues/362)
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/collaborator/collaborator.component.ts
> +  public onFollowClick(projectId: number) {
Documentation missing

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/collaborator/collaborator.component.ts
> +  public isProduction(): boolean {
Documentation missing

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.html
> +      <!-- <img src="https://www.rover.com/blog/wp-content/uploads/2019/06/bernese-mountain-dog-1177074_1920-960x540.jpg" alt="project-detail-image"> -->
Commented out code, probably should be removed or explained why it's here

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +.modal-dialog{
```suggestion
.modal-dialog {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +      .title{
```suggestion
      .title {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +    .hover{
```suggestion
    .hover {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +      &:hover{
```suggestion
      &:hover {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +        color: $accent-color-red-primary!important;
```suggestion
        color: $accent-color-red-primary !important;
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +      .popover{
```suggestion
      .popover {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +        .arrow::before{
```suggestion
        .arrow::before {
```

2020-12-02 23:07 UTC, Brend-Smits commented on src/app/modules/project/details/details.component.scss
> +      .collaborators{
```suggestion
      .collaborators {
```

2020-12-03 10:11 UTC, juliaslaats commented on src/app/modules/project/details/details.component.html
> +      <!-- in this place should be a image or a bootstrap carrousel after the wizzard is finished
English mistakes
"**on this spot** should be **an** image or a bootstrap carrousel after the **wizard** is finished"

2020-12-03 10:26 UTC, juliaslaats requested changes
Looks pretty good! I do notice that there's a couple things that are different than on the designs. Not sure if that's on purpose and I missed the memo on it, but maybe you could look at:
- The design says 'contributors' wit a tooltip instead of just 'uploader' on the top info
- The design says 'contributors' instead of 'collaborators' in the bottom menu. 
- The designs have a close button in the right top corner of the screen, that I'm missing here. 
- The designs have an edit-button aligned on the right in the bottom menu, that I'm missing here.

And then there's a couple things I noticed that are not necessarily related to the designs
- The 'uploader' is not included as a collaborator in the menu on the bottom
- The 'give feedback' button jumps when you click on a detail page. 
- The likes are 0 on the overview page, but 120 on the detail page. 

If the differences from the designs were on purpose, or if I had an outdated version of the designs, I apologize. Please let me know 😄

2020-12-03 10:44 UTC, liekevdvoort commented
The design says 'contributors' wit a tooltip instead of just 'uploader' on the top info
Yes but i forgot the uploader in the designs and we already have the collaborators in the tab
The design says 'contributors' instead of 'collaborators' in the bottom menu.
Yes but dex already used collaborators so i wanted to keep it consistent
The designs have a close button in the right top corner of the screen, that I'm missing here.
Needs to be added but isn't as easy as thought so i wanted to do this in a new issue
The designs have an edit-button aligned on the right in the bottom menu, that I'm missing here.
you mean the settings this is only showed when it is your project or you are admin

And then there's a couple things I noticed that are not necessarily related to the designs

The 'uploader' is not included as a collaborator in the menu on the bottom
I don't know if they should i think they are not included now
The 'give feedback' button jumps when you click on a detail page.
Can't be prevented because of scroll locking and the scrollbar of the detail modal
The likes are 0 on the overview page, but 120 on the detail page.
The likes are placeholders and won't be shown on production

@juliaslaats

2020-12-03 10:47 UTC, waltersajtos commented
Hey, thanks for the pointers. I will answer them inline

> Looks pretty good! I do notice that there's a couple things that are different than on the designs. Not sure if that's on purpose and I missed the memo on it, but maybe you could look at:
> 
> * The design says 'contributors' wit a tooltip instead of just 'uploader' on the top info
- We decided to go with the author there since the contributors are shown in the tab on the bottom.
> * The design says 'contributors' instead of 'collaborators' in the bottom menu.
- We decided to change this because we call it collaborators in the backend as well, if we use different names it becomes confusing.
> * The designs have a close button in the right top corner of the screen, that I'm missing here.
- 
> * The designs have an edit-button aligned on the right in the bottom menu, that I'm missing here.
- I'm not too sure what you mean by the edit-button. If you mean the cog-popOver then you need to make sure that it is actually your project. If you don't have permission to edit it the cog will not be shown.
> 
> And then there's a couple things I noticed that are not necessarily related to the designs
> 
> * The 'uploader' is not included as a collaborator in the menu on the bottom
- If this is an issue it is a backend issue
> * The 'give feedback' button jumps when you click on a detail page.
- This happens because the scroll bar moves up to the modal, if this is a big problem we need to make a hacky solution which I don't prefer.
> * The likes are 0 on the overview page, but 120 on the detail page.
- This made the styling easier, the likes are hidden in production until we complete the implementation of them so this shouldn't be an issue
> 
> If the differences from the designs were on purpose, or if I had an outdated version of the designs, I apologize. Please let me know 😄

2020-12-03 12:48 UTC, juliaslaats approved these changes
Thanks for addressing my comments! It looks good to me 👍

2020-12-03 14:55 UTC, Ruby77 requested changes
Looks really nice again 😄.

One small question:
![image](https://user-images.githubusercontent.com/55654104/101044459-a2009d00-357f-11eb-9844-6a8397194291.png)
When I tried to close the settings, I clicked somewhere on the screen expecting the popup would hide (just like for the sign out menu). I noticed it only hides whenever I clicked on the settings button. Is this a specific choice, why it won't hide whenever I click somewhere else?

2020-12-03 14:55 UTC, Ruby77 commented on src/app/modules/project/overview/overview.component.ts
> +  }
I would suggest adding documentation to these methods as well.

2020-12-03 16:49 UTC, waltersajtos commented
> Looks really nice again 😄.
> 
> One small question:
> ![image](https://user-images.githubusercontent.com/55654104/101044459-a2009d00-357f-11eb-9844-6a8397194291.png)
> When I tried to close the settings, I clicked somewhere on the screen expecting the popup would hide (just like for the sign out menu). I noticed it only hides whenever I clicked on the settings button. Is this a specific choice, why it won't hide whenever I click somewhere else?

I switched from a tooltip to a popover because tooltips do not allow the anchor tags. I forgot to check the behavior, nice catch!

2020-12-04 15:04 UTC, Ruby77 approved these changes
Nice 🎉

2020-12-07 09:53 UTC, Brend-Smits approved these changes
Nice work everyone!

2020-12-07 09:53 UTC, merged