Bugfix/405 setup og tags
DigitalExcellence/dex-frontend pull request #406
Opened 2021-01-05 14:26 UTC by Niekvandam

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [X] I updated the changelog with an end-user readable description
-   [X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

You can set up a localtunnel/NGROK network  and link this URL to any service that supports OG tags (facebook, twitter, discord, slack etc.). However, in this case the image will not be resolved, as it is linking to the dex.software site, which - at this point - does not have the appropriate header image yet (until the pull request is approved). 

When linked, you can check whether or not the description, URL and title work as expected. The header image can be checked by changing the link to the index.html file to whatever URL got generated and linking it to any service as listed above afterwards. 

example:
`  <meta property="og:image" content="https://dex.software/assets/images/dex-x.png">` 
becomes 
`  <meta property="og:image" content="https://rare-bird-82.loca.lt/assets/images/dex-x.png">`

## Link to issue

Closes: #405

2021-01-05 14:35 UTC, liekevdvoort approved these changes

2021-01-06 11:37 UTC, Brend-Smits requested changes

2021-01-06 11:37 UTC, Brend-Smits commented on src/index.html
> +  <meta property="twitter:domain" content="rare-bird-82.loca.lt">
rare-bird-82.loca.lt ?

2021-01-06 12:22 UTC, Brend-Smits approved these changes
Awesome, thanks for your contribution!

2021-01-06 16:42 UTC, liekevdvoort approved these changes

2021-01-07 08:03 UTC, merged