Changed max-width
DigitalExcellence/dex-frontend pull request #455
Opened 2021-04-04 22:20 UTC by waltersajtos

## Description

Quick fix for the privacy modal

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Open an incognito tab
2. Go to the login page
3. Click FHICT and check if the privacy modal looks good on desktop and mobile

## Link to issue

Closes: #426

2021-04-08 12:22 UTC, RubenFricke reviewed
Implementation and result look great, thanks! 
Although, a small request (maybe a little bit out of scope), the alerts aren't responsive as well. It's up to you whether you want to pick this up in this issue or create a new issue. 
![image](https://user-images.githubusercontent.com/55654104/114025641-a1517d80-9875-11eb-9141-7f89140d7b7b.png)
Good work 🔥

2021-04-08 18:51 UTC, waltersajtos commented
![image](https://user-images.githubusercontent.com/32552097/114080914-35d6d280-98ac-11eb-81d5-c7ef220a58af.png)
![image](https://user-images.githubusercontent.com/32552097/114080925-38392c80-98ac-11eb-9daa-0fa780043013.png)
@RubenFricke

2021-04-13 12:32 UTC, RubenFricke requested changes
The implementation and code look good as usual. One note I had to make.

2021-04-13 12:32 UTC, RubenFricke commented on src/app/components/alert/alert.component.scss
> +    max-width: 60%;
Why set the max-width to 60%? 
![image](https://user-images.githubusercontent.com/55654104/114552235-a98a2e00-9c64-11eb-803c-b7dd06829fe4.png)
And adding margin would improve the experience as well in my opinion.

2021-04-24 18:09 UTC, RubenFricke approved these changes
Everything works, thanks. I updated your CHANGELOG because the issue has grown a little and you accidentally added this change to the wrong release in the CHANGELOG file 😉

2021-04-26 13:33 UTC, niraymak approved these changes
Great work! 👍

2021-04-26 13:57 UTC, RubenFricke approved these changes

2021-04-26 13:59 UTC, niraymak approved these changes

2021-04-26 16:50 UTC, merged