471-fix-import-project-without-short-description
DigitalExcellence/dex-frontend pull request #472
Opened 2021-04-19 08:32 UTC by waltersajtos

## Description

This pull request fixes an issue that broke the wizard when the user tried to import a project without a short desciprtion

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Log in
2. Click on Github data source
3. Import this link https://github.com/waltersajtos/oeloes.resources
4. Validate that there is weird behavior on the completed steps (for example the collaborators are imported but not marked as imported)
5. Validate that step 1 is not completed which results in not being able to upload the project.

## Link to issue

Closes: #471

2021-04-19 11:37 UTC, RubenFricke requested changes
Looks great and works flawlessly. Perfectly solved the issue, great work, and thanks for the pull request 🥇. Since we can import projects without a short description now, which is great and of course how it's meant to be, a new bug is possible to reproduce by following the next steps:
- Import the project by this Uri: https://github.com/waltersajtos/oeloes.resources
- Go to step 3 and enter a short description
- Press next
- Go back to step 1
- Import a project that doesn't have a short description (for simplicity we can reuse this Uri https://github.com/waltersajtos/oeloes.resources) and press the import button
- Validate that the short description step is marked as completed but no short description is entered.
- By completing all the other steps and trying to click on 'Finish' you will get this alert: 
![image](https://user-images.githubusercontent.com/55654104/115229529-72f45d80-a113-11eb-8362-96a9ba0791df.png)

I think old data won't get deleted if no new data will override the old one because I also noticed that the icon will remain uploaded. I don't know if this is the wanted behavior because maybe some crucial information won't get updated/deleted if you import a new project. Maybe we can reset the whole form? @DigitalExcellence/frontend Anyone has some opinions they would like to share on this?

2021-04-26 13:09 UTC, niraymak approved these changes

2021-04-26 13:10 UTC, niraymak approved these changes

2021-04-26 13:49 UTC, RubenFricke approved these changes

2021-04-26 13:53 UTC, merged