Feature/380 redesign homepage
DigitalExcellence/dex-frontend pull request #476
Opened 2021-04-23 13:56 UTC by macfleury-2000

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ X ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ X ] My code follows the style guidelines of this project
-   [ X ] I have performed a self-review of my own code
-   [ X ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ X ] I updated the changelog with an end-user readable description
-   [ X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Go to the homepage
2. Click on random buttons, do they go to the right place?
3. Check if everything is readable on your screen

## Link to issue

Closes: #380

2021-04-24 15:48 UTC, waltersajtos commented
The sonar cloud errors should be fixed, there are a lot of things it doesn't like
[code_smells](https://sonarcloud.io/project/issues?id=DigitalExcellence_dex-frontend&pullRequest=476&resolved=false&types=CODE_SMELL) &
[bugs](https://sonarcloud.io/project/issues?id=DigitalExcellence_dex-frontend&pullRequest=476&resolved=false&types=BUG)

The way this picture is cut off seems a bit odd, is it meant to look this way?
![afbeelding](https://user-images.githubusercontent.com/32552097/115964474-f30c3000-a524-11eb-9ada-be2422ff7e63.png)

Also in the hover effects on the cards, the shapes seem to transform too. Is that expected?
https://gyazo.com/78dbcc9c08cd0d79ddfedc9963dde143

2021-04-26 07:14 UTC, waltersajtos requested changes
The sonar cloud errors should be fixed, there are a lot of things it doesn't like
[code_smells](https://sonarcloud.io/project/issues?id=DigitalExcellence_dex-frontend&pullRequest=476&resolved=false&types=CODE_SMELL) & [bugs](https://sonarcloud.io/project/issues?id=DigitalExcellence_dex-frontend&pullRequest=476&resolved=false&types=BUG)

The way this picture is cut off seems a bit odd, is it meant to look this way?
![afbeelding](https://user-images.githubusercontent.com/32552097/115964474-f30c3000-a524-11eb-9ada-be2422ff7e63.png)

Also in the hover effects on the cards, the shapes seem to transform too. Is that expected?
https://gyazo.com/78dbcc9c08cd0d79ddfedc9963dde143

2021-04-26 09:15 UTC, niraymak commented
First impression was good!

However I had some remarks:
- Add your project redirects to 404 page.
- Pipeline checks are not succeeding yet.
- I was wondering why we use the image with the monitor on it with a Mac on it, haven't seen it before? I think the monitor
- Mobile view looks kinda weird:
![image](https://user-images.githubusercontent.com/44868678/116057899-8eb1b380-a67f-11eb-9f39-b3b2f1c62ff4.png)
![image](https://user-images.githubusercontent.com/44868678/116057828-7a6db680-a67f-11eb-9ec9-f809761e5570.png)

In my opinion the partners tab would work with 1 Fontys and 1 Delta aswell: 
![image](https://user-images.githubusercontent.com/44868678/116058492-30390500-a680-11eb-8f6c-1223d449b1b1.png)

I think the same partners twice looks weird on mobile view:
![image](https://user-images.githubusercontent.com/44868678/116058934-a0478b00-a680-11eb-814e-f354cf664b75.png)

2021-04-28 13:27 UTC, niraymak requested changes
Responsive view looks a bit weird for the highlights:

![image](https://user-images.githubusercontent.com/44868678/116411373-f14cb000-a835-11eb-9f04-79ed5b0c9a7c.png)

I think this orange block looks kind of weird in responsive mode: 

![image](https://user-images.githubusercontent.com/44868678/116411491-0f1a1500-a836-11eb-88ec-99ac856cf1e1.png)

![image](https://user-images.githubusercontent.com/44868678/116411589-25c06c00-a836-11eb-8f96-6c7846b71aea.png)

I also left some comments.

Keep up the good work! :)

2021-04-28 13:27 UTC, niraymak commented on src/app/modules/home/container-right/container-right.component.html
> +<div class="container-left">
shouldn't this be container-right?

2021-04-28 13:27 UTC, niraymak commented on src/app/modules/home/container-right/container-right.component.html
> +  <img src="/assets/images/homepage/mockup-wizzard.png" alt="mockup wizzard"/>
```suggestion
  <img src="/assets/images/homepage/mockup-wizard.png" alt="mockup wizard"/>
```

2021-04-28 13:27 UTC, niraymak commented on src/app/modules/home/highlight-slider/highlight-slider.component.html
> +      <p>Stukje dex algemeen niet te lang, lorem ipsum dolor sit amet lorem ipsum dolor sit amet.</p>
Replace with temporary content instead of lorem ipsum

2021-04-28 13:27 UTC, niraymak commented on src/app/modules/home/container-right/container-right.component.ts
> +    if (this.router.url === '/project/add/source') {
```suggestion
    if (this.router.url === '/project/add') {
```

2021-04-28 13:27 UTC, niraymak commented on src/app/modules/home/container-right/container-right.component.ts
> +      this.router.navigate(['project/add/source']);
```suggestion
      this.router.navigate(['project/add']);
```

2021-04-28 14:24 UTC, waltersajtos commented
Just a quick comment, the security issue that solar cloud is complaining about doesn't apply to our use-case. The empty block error shouldn't be an issue either, it's easy to have the file in place if we ever need to apply styling to the main block.

2021-04-28 14:35 UTC, waltersajtos requested changes

2021-04-28 14:35 UTC, waltersajtos commented on src/app/modules/home/container-left/container-left.component.ts
> +  public viewAllProjects() {
How could the current url be `/project/overview` here? And if it was, why would you reload the page?

2021-04-28 14:35 UTC, waltersajtos commented on src/app/modules/home/container-right/container-right.component.ts
> +    if (this.router.url === '/project/add/source') {
How could the current url be `/project/add` here? And if it was, why would you reload the page?

2021-04-29 10:26 UTC, niraymak requested changes
One small thing left!

2021-04-29 10:26 UTC, niraymak commented on src/app/modules/home/highlight-slider/highlight-slider.component.html
> +      <h2>DeX - for digital excellence</h2>
```suggestion
      <h2>DeX - for Digital Excellence</h2>
```

2021-04-29 11:13 UTC, waltersajtos approved these changes

2021-04-29 11:45 UTC, niraymak approved these changes
There still are some things that should be improved in responsive view. But we agreed to pick this up in a seperate issue so we can add this feature to the release. Happy to have this new home page :)

2021-04-29 11:45 UTC, merged