Project wizard improvements
DigitalExcellence/dex-frontend pull request #487
Opened 2021-05-10 10:36 UTC by waltersajtos

## Description

While testing the wizard we ran into some small issues, this pull request addresses those issues.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

## Link to issue

Closes: #462

2021-05-16 10:01 UTC, RubenFricke reviewed
Everything worked just as you mentioned. Good work Walter! The only remark I have is that the icon fix you made is not mentioned in the CHANGELOG.  

With this pull request, you would like to close #460, but I think you only tackled the visuals and not the interaction part? (I can still click 2 > 3 >4 and not 2 > 4) Maybe we can schedule a meeting to talk about this? 

In the created issue it was mentioned that the manual flow should be the first option. I don't understand the reason for this @niraymak. In my opinion, it makes more sense for it to be the last option because we want to stimulate users to import projects from external sources, thus the first options. If all these options are not applicable, we should offer the manual option as last resort. @liekevdvoort what are your thoughts on this?

2021-05-17 07:14 UTC, liekevdvoort commented on src/app/modules/project/add/main/wizard/wizardPages/default/project-link/project-link.component.ts
> +    console.log(this.selectedSource);
I don't know I think it should be logical for the first option to be the option that is always usable with or without a link. and if you do have a GitHub project I think you will recognize the logo way faster than the person without a supported import searching for the default option.

But I don't have a really strong opinion on it just my thoughts.

2021-05-26 20:59 UTC, waltersajtos commented
I will include #492 in this PR

2021-05-27 12:23 UTC, niraymak requested changes
Great job! Works like a charm!

 Only found a mistake in the changelog. Will approve when commited 👍

2021-05-27 12:23 UTC, niraymak commented on CHANGELOG.md
> +- Clicking to the next step in the wizard step-header will now skip the step & removed orange progress bar
```suggestion
- Clicking to the next step in the wizard step-header will now skip the step & removed orange progress bar - [#460](https://github.com/DigitalExcellence/dex-frontend/issues/460)
```

I think it became 2 lines by accident

2021-05-27 12:23 UTC, niraymak commented on CHANGELOG.md
> +  - [#460](https://github.com/DigitalExcellence/dex-frontend/issues/460)
```suggestion
```
Not sure if this suggestion removes the line..

2021-05-27 12:38 UTC, niraymak approved these changes

2021-05-27 17:09 UTC, niraymak approved these changes

2021-05-27 18:19 UTC, RubenFricke approved these changes
You tackled a lot of different things and it all worked flawlessly. Compliments 🥂 !

2021-05-27 18:27 UTC, merged