Open project detail on homepage instead of redirecting to overview page
DigitalExcellence/dex-frontend pull request #488
Opened 2021-05-10 12:50 UTC by waltersajtos

## Description

Implementation of the new homepage designs

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Go to the homepage
2. Check if all buttons redirect to the expected page
3. Check if everything looks good on all resolutions
4. Check if the modals open on the homepage and work as expected

## Link to issue

Closes: #380

2021-05-15 13:31 UTC, niraymak commented
Any changes made?

Noticed that one highlight was not showing properly in responsive view.
![Uploading image.png…]()

2021-05-15 14:32 UTC, waltersajtos commented
> 
> 
> Any changes made?
> 
> Noticed that one highlight was not showing properly in responsive view.
> ![image](https://user-images.githubusercontent.com/44868678/118363019-adc2a780-b592-11eb-9dd8-2b41708395f2.png)

I only changed the highlight logic, no styling. @liekevdvoort was going to look at it iirc.

2021-05-24 13:43 UTC, niraymak commented
Except for the highlights (highlight description and title were showing on the same place at some resolutions). 

I think they will move to a carrousel view, right?

2021-05-24 13:48 UTC, niraymak commented
Not sure if this can and should be fixed, but when loading the page for a split second it looks like this: 
![image](https://user-images.githubusercontent.com/44868678/119356913-3f26cd80-bca7-11eb-9b2e-9200452fb10d.png)

The background image is stretched and the text moves from the center to the left. This probably has something to do with the highlights loading in.

2021-05-27 12:33 UTC, niraymak requested changes
Good work, excited for this one! 🥇 

Had one remark: when you create a highlight it is required to at least enter 75 characters.
I added one with around 75 characters, which was not completly readable for me. Maybe we should change the requirements?

![image](https://user-images.githubusercontent.com/44868678/119826456-527ca780-bef8-11eb-9766-80a35335d860.png)


Please also update changelog.

2021-05-27 12:33 UTC, niraymak commented on CHANGELOG.md
> +
Missing changelog for homepage.

2021-05-27 13:02 UTC, niraymak submitted a review, later dismissed

2021-05-27 17:10 UTC, niraymak submitted a review, later dismissed

2021-06-02 13:25 UTC, niraymak approved these changes
🥇

2021-06-02 13:27 UTC, RubenFricke approved these changes
Great! Well done 🎉

2021-06-02 13:27 UTC, merged