Implement categories
DigitalExcellence/dex-frontend pull request #496
Opened 2021-05-27 11:51 UTC by waltersajtos

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a project and add a category
2. Create a project without a category
3. Go to the overview page and make sure both are displayed correctly (detail page too)
4. Edit the project with a category, change to a different category and check step 3.
5. Delete the category from the project and check step 3.

## Link to issue

Closes: #475 
Closes: #493 
Closes: #351

2021-06-02 11:27 UTC, niraymak requested changes
Everything works fine, I think we can still improve on the styling in the filter menu.
I thought the text was too close to the checkbox. I guess we can add a bit of spacing there?

On my screen a maximum of 12 categories was showing up. I guess we could make this a scrollable list? I think we should merge it and improve on it next sprint. What's your opinion about this? @RubenFricke 
![image](https://user-images.githubusercontent.com/44868678/120472216-e8577d00-c3a5-11eb-8980-151ced6a1fa5.png)

2021-06-02 11:27 UTC, niraymak commented on src/app/modules/project/overview/overview.component.html
> +              <label [for]="category.name">{{category.name}}</label>
I guess we could improve styling of this one. Maybe merge it and improve next sprint?

2021-06-04 07:43 UTC, RubenFricke approved these changes

2021-06-04 07:59 UTC, niraymak approved these changes
🥇

2021-06-04 08:01 UTC, RubenFricke approved these changes

2021-06-04 08:12 UTC, merged