Implement multiple call to actions
DigitalExcellence/dex-frontend pull request #533
Opened 2021-06-22 12:31 UTC by waltersajtos

## Description

In the original designs of the detail page, it was possible to add multiple call-to-action options. This pull request will implement these designs and functionality.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Add a project with 3 call-to-action.
2. Go to the overview page and check if the project has the call to action buttons with the URLs.
3. Edit your project and change a url and remove a call to action button.
4. Validate the changes came through.

## Link to issue

Closes: #454

2021-06-25 08:25 UTC, niraymak requested changes
The project categories don't show as active anymore on the edit page.
![image](https://user-images.githubusercontent.com/44868678/123390044-c9aa6780-d59a-11eb-878c-c579eac1ab31.png)

Styling beneath the call to actions on the edit page seemed a bit odd. Is the styling on the buttons updated on purpose?
![image](https://user-images.githubusercontent.com/44868678/123390139-df1f9180-d59a-11eb-9d3e-61bfb71ef671.png)

2021-06-29 10:11 UTC, niraymak approved these changes
😄

2021-06-29 11:02 UTC, niraymak approved these changes
😄

2021-06-29 12:59 UTC, RubenFricke approved these changes

2021-06-29 13:00 UTC, merged