Created share button on project details modal
DigitalExcellence/dex-frontend pull request #565
Opened 2021-09-07 19:39 UTC by 1SvenHansen

Created share button on project details modal copying the user's current URL to the user's clipboard.

## Description

Giving the user the possibility to share the currently opened project. By clicking on the share button the user's URL gets copied to her/his clipboard.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Go to the projects overview.
2. Select a project so the projects detail modal will open.
3. Click on the 'Copy url' button.
4. Try pasting your clipboard in a fresh tab.
5. Run the pasted clipboards text and see if it goes to the selected project from step 2.

## Link to issue

Closes: #442

2021-09-08 08:06 UTC, MeesvanStraten requested changes
Nice work! A few remarks.
- Could you use a share icon like: [this](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F808790%2Ffollow_join_network_share_icon&psig=AOvVaw1_xX6mGjZAVvYPhB-zYgZM&ust=1631174243602000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCODZqtzz7vICFQAAAAAdAAAAABAI)

- Change text to "Share project url" and when copied to something like"Project url copied to clipboard" or similair.
- Have the button next to the embed button, than we have all sharing / embedding functionalities next to each other.

![image](https://user-images.githubusercontent.com/41986758/132470053-9124bfeb-32a0-426d-8bcc-6d9ff3979d56.png)

2021-09-09 15:49 UTC, MeesvanStraten requested changes
Looks good! Nice job. One last thing, the build checks fail because of a linter issue. Can you have a look?

2021-09-09 17:04 UTC, 1SvenHansen commented
@MeesvanStraten I was indeed looking into that one as you can see in the last commits haha, but I was unable to finish it before going home. My bad if it requested a new pull request, didn't mean so. Thanks for the heads up, again :)

2021-09-10 07:34 UTC, DaveBouman submitted a review, later dismissed

2021-09-10 07:39 UTC, DaveBouman approved these changes

2021-09-10 07:42 UTC, DaveBouman submitted a review, later dismissed

2021-09-10 07:44 UTC, BartvanEijkelenburg approved these changes

2021-09-10 09:31 UTC, MeesvanStraten approved these changes

2021-09-10 09:40 UTC, BartvanEijkelenburg approved these changes

2021-09-10 12:49 UTC, merged