Fixed modal disappearing highlight form
DigitalExcellence/dex-frontend pull request #576
Opened 2021-09-21 07:35 UTC by NealGeilen

## Description

Fixed highlight project modal, not disappearing when clicking out of it. 

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Log in as an admin
2. Open up a project, click the cogwheel.
3. On popup click higlight settings.
4. Try to click outside the modal. It does not work.

## Link to issue

Closes: #569

2021-09-22 09:03 UTC, 1SvenHansen requested changes
Hi Neal, a quick tip that I got told about last week; perhaps try changing the Changelog.md by adding the changes you make. This can be used later for e.g. automated version deployment.
You can change the file by editing it via github editor as it is ignored by git.

2021-09-23 12:37 UTC, MeesvanStraten commented
@NealGeilen  I tried testing it but had some problems. With chrome I did not have any problems clicking the highlight away (even before the fix so on staging and prod it works fine). In this branch chrome works fine, but for some reasons i am getting CORS errors when trying to login on Firefox. Did you tested this on chrome and firefox? and did you have problems before the fix with chrome? If you tested with firefox where you able to succesfully login ? or also CORS errors in the developer console?

2021-09-28 07:54 UTC, 1SvenHansen approved these changes

2021-09-28 08:18 UTC, BartvanEijkelenburg approved these changes
Works good. Clicking outside the modal just dissappears now.

2021-09-28 08:48 UTC, merged